---@meta mods.calendar

---@alias modsCalendarWeekday 1|2|3|4|5|6|7
---@alias modsCalendarMonth 1|2|3|4|5|6|7|8|9|10|11|12
---@alias modsCalendarMonthday 1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31

---
---Calendar and date helpers.
---
---## Usage
---
---```lua
---cal = require "mods.calendar"
---
---print(cal.weekday(2026, 3, 26)) --> 4
---```
---
---@class mods.calendar
---@field JANUARY    1
---@field FEBRUARY   2
---@field MARCH      3
---@field APRIL      4
---@field MAY        5
---@field JUNE       6
---@field JULY       7
---@field AUGUST     8
---@field SEPTEMBER  9
---@field OCTOBER   10
---@field NOVEMBER  11
---@field DECEMBER  12
---
---@field MONDAY    1
---@field TUESDAY   2
---@field WEDNESDAY 3
---@field THURSDAY  4
---@field FRIDAY    5
---@field SATURDAY  6
---@field SUNDAY    7
---
---Month names indexed from `1` to `12`.
---
---```lua
---print(cal.months[1])  --> January
---print(cal.months[12]) --> December
---```
---@field months mods.List<string>
---
---Weekday names indexed from `1` (Monday) to `7` (Sunday).
---
---```lua
---print(cal.days[1]) --> Monday
---print(cal.days[7]) --> Sunday
---```
---@field days mods.List<string>
---
---The default first weekday field.
---
---```lua
---print(cal.firstweekday) --> 1
---cal.firstweekday = cal.SUNDAY
---print(cal.firstweekday) --> 7
---```
---
---> [!NOTE]
--->
---> Reading or writing this property is equivalent to calling
---> `getfirstweekday()` or `setfirstweekday()`.
---
---@field firstweekday modsCalendarWeekday
local M = {}

---
---Return the default first weekday.
---
---```lua
---print(cal.getfirstweekday()) --> 1
---```
---
---> [!NOTE]
--->
---> This returns the same value as `cal.firstweekday`.
---
---@return modsCalendarWeekday firstweekday
---@nodiscard
function M.getfirstweekday() end

---
---Set the default first weekday.
---
---```lua
---cal.setfirstweekday(cal.SUNDAY)
---```
---
---> [!NOTE]
--->
---> This updates the same value as
---> `cal.firstweekday = ...`.
---
---@param firstweekday modsCalendarWeekday
function M.setfirstweekday(firstweekday) end

---
---Iterate weekday numbers for one full week.
---
---```lua
---local weekdays = {}
---for day in cal.weekdays() do
---  weekdays[#weekdays + 1] = day
---end
---print(table.concat(weekdays, ", ")) --> "1, 2, 3, 4, 5, 6, 7"
---```
---
---@section Iterators
---@param firstweekday? modsCalendarWeekday
---@return fun():modsCalendarWeekday iter
---@nodiscard
function M.weekdays(firstweekday) end

---
---Return `true` for leap years.
---
---```lua
---print(cal.isleap(2024)) --> true
---```
---
---@section Calendar Calculations
---@param year integer
---@return boolean isLeap
---@nodiscard
function M.isleap(year) end

---
---Return the number of leap years from `y1` up to but not including `y2`.
---
---```lua
---print(cal.leapdays(2000, 2025)) --> 7
---```
---
---@section Calendar Calculations
---@param y1 integer
---@param y2 integer
---@return integer count
---@nodiscard
function M.leapdays(y1, y2) end

---
---Return weekday number where Monday is `1` and Sunday is `7`.
---
---```lua
---print(cal.weekday(2026, 3, 26)) --> 4
---```
---
---@section Calendar Calculations
---@param year integer
---@param month modsCalendarMonth
---@param day modsCalendarMonthday
---@return modsCalendarWeekday weekday
---@nodiscard
function M.weekday(year, month, day) end

---
---Return the first weekday and number of days for a month.
---
---```lua
---wday, ndays = cal.monthrange(2026, 2)
---print(wday, ndays) --> 7 28
---```
---
---@section Calendar Calculations
---@param year integer
---@param month integer
---@return modsCalendarWeekday weekday
---@return integer ndays
---@nodiscard
function M.monthrange(year, month) end

---Iterate `(year, month, day, weekday)` tuples for a full calendar grid.
---
---```lua
---local mods = require "mods"
---
---local List = mods.List
---local cal = mods.calendar
---local str = mods.str
---
---local header = cal.weekheader(2)
---local lines = List({
---  str.center(("%s %d"):format(cal.months[cal.FEBRUARY], 2026), #header),
---  header,
---})
---
---local cells = List()
---for _, m, d, _ in cal.monthdays(2026, cal.FEBRUARY) do
---  cells:append(m == cal.FEBRUARY and ("%2d"):format(d) or "  ")
---  if #cells == 7 then
---    lines:append(cells:join(" "))
---    cells = List()
---  end
---end
---
---print(lines:join("\n"))
-----    February 2026
----- Mo Tu We Th Fr Sa Su
-----                    1
-----  2  3  4  5  6  7  8
-----  9 10 11 12 13 14 15
----- 16 17 18 19 20 21 22
----- 23 24 25 26 27 28
---```
---
---@section Iterators
---@param year integer
---@param month modsCalendarMonth
---@param firstweekday? modsCalendarWeekday
---@return fun():year:integer,month:modsCalendarMonth,day:modsCalendarMonthday,weekday:modsCalendarWeekday iter
---@nodiscard
function M.monthdays(year, month, firstweekday) end

---
---Return the formatted weekday header string.
---
---```lua
---print(cal.weekheader(1, cal.SUNDAY)) --> "S M T W T F S"
---print(cal.weekheader(2, cal.SUNDAY)) --> "Su Mo Tu We Th Fr Sa"
---print(cal.weekheader(3, cal.SUNDAY)) --> "Sun Mon Tue Wed Thu Fri Sat"
---```
---
---@section Formatting
---@param width? integer
---@param firstweekday? modsCalendarWeekday
---@return string header
---@nodiscard
function M.weekheader(width, firstweekday) end

return M
