---@diagnostic disable: undefined-field

--[[
  Most test cases were ported from CPython's pathlib tests.
  Adapted and ported to Lua/Busted for this project's API and conventions.
  Source: https://github.com/python/cpython/tree/main/Lib/test/test_pathlib
  License: Python Software Foundation License Version 2 (PSF-2.0).
  Copyright (c) 2001 Python Software Foundation; All Rights Reserved.
]]

local lfs = require "lfs"
local mods = require "mods"
local helpers = require "spec.helpers"

local Set = mods.Set
local ntpath = mods.ntpath
local path = mods.path
local posixpath = mods.posixpath
local runtime = mods.runtime
local tbl = mods.tbl
local with_env = helpers.with_env

local fmt = string.format

-- stylua: ignore
local tests = {
  anchor = {
    "common",
    {{ ""            }, { ""         }},
    {{ "a/b"         }, { ""         }},
    "posix",
    {{ "/"           }, { "/"        }},
    {{ "/a/b"        }, { "/"        }},
    "windows",
    {{ [[a\b]]       }, { ""         }},
    {{ [[\]]         }, { [[\]]      }},
    {{ [[\a\b]]      }, { [[\]]      }},
    {{ "c:"          }, { "c:"       }},
    {{ "c:a/b"       }, { "c:"       }},
    {{ "c:/a/b"      }, { [[c:\]]    }},
    {{ [[c:\]]       }, { [[c:\]]    }},
    {{ [[c:\a\b\]]   }, { [[c:\]]    }},
    {{ [[\\a\b]]     }, { [[\\a\b\]] }},
    {{ [[\\a\b\]]    }, { [[\\a\b\]] }},
    {{ [[\\a\b\c\d]] }, { [[\\a\b\]] }},
  },
  as_posix = {
    "common",
    {{ "a"               }, { "a"             }},
    {{ "a/b"             }, { "a/b"           }},
    {{ "a/b/c"           }, { "a/b/c"         }},
    {{ "/"               }, { "/"             }},
    {{ "/a/b"            }, { "/a/b"          }},
    {{ "/a/b/c"          }, { "/a/b/c"        }},
    "windows",
    {{ [[a\b]]           }, { "a/b"           }},
    {{ [[a\b\c]]         }, { "a/b/c"         }},
    {{ [[C:\a\b]]        }, { "C:/a/b"        }},
    {{ [[\\srv\share\a]] }, { "//srv/share/a" }},
  },
  as_uri = {
    "posix",
    {{ "/"                  }, { "file:///"                  }},
    {{ "/a/b.c"             }, { "file:///a/b.c"             }},
    {{ "/a/b%#c"            }, { "file:///a/b%25%23c"        }},
    {{ "/a/bé"              }, { "file:///a/b%C3%A9"         }},
    "windows",
    {{ "/a/b"               }, { nil, "path is not absolute" }},
    {{ "c:a/b"              }, { nil, "path is not absolute" }},
    {{ "c:/"                }, { "file:///c:/"               }},
    {{ "c:/a/b.c"           }, { "file:///c:/a/b.c"          }},
    {{ "c:/a/b%#c"          }, { "file:///c:/a/b%25%23c"     }},
    {{ "//some/share/"      }, { "file://some/share/"        }},
    {{ "//some/share/a/b.c" }, { "file://some/share/a/b.c"   }},
  },
  commonprefix = {
    "common",
    {{{                                           }}, { ""                }},
    {{{ ""                  , "abc"               }}, { ""                }},
    {{{ "abc"               , "abd"               }}, { "ab"              }},
    {{{ "Xbcd"              , "Xb"                }}, { "Xb"              }},
    {{{ "abcX"              , "abcd"              }}, { "abc"             }},
    {{{ "aXc"               , "aX"                }}, { "aX"              }},
    {{{ "abc"               , "abc"               }}, { "abc"             }},
    {{{ "abc"               , "xbc"               }}, { ""                }},
    {{{ "/a/b"              , "/a/c"              }}, { "/a/"             }},
    {{{ "/home/swenson/spam", "/home/swen/spam"   }}, { "/home/swen"      }},
    {{{ "/home/swen/spam"   , "/home/swen/eggs"   }}, { "/home/swen/"     }},
    {{{ "/home/swen/spam"   , "/home/swen/spam"   }}, { "/home/swen/spam" }},
    {{{ "home:swenson:spam" , "home:swen:spam"    }}, { "home:swen"       }},
    {{{ ":home:swen:spam"   , ":home:swen:eggs"   }}, { ":home:swen:"     }},
    {{{ ":home:swen:spam"   , ":home:swen:spam"   }}, { ":home:swen:spam" }},
    {{{ "/home/swen/spam"   , "/home/swen/spam"   }}, { "/home/swen/spam" }},
    "windows",
    {{{ [[\home\swen\spam]] , [[\home\swen\eggs]] }}, { [[\home\swen\]]   }},
  },
  parents = {
    "posix",
    {{ "a/b/c"        }, {{ "a/b"      , "a"       , "." }}},
    {{ "/a/b/c"       }, {{ "/a/b"     , "/a"      , "/" }}},
    "windows",
    {{ "a/b/c"        }, {{ [[a\b]]    , "a"       , "." }}},
    {{ "c:a/b"        }, {{ "c:a"      , "c:"            }}},
    {{ "c:/a/b"       }, {{ [[c:\a]]   , [[c:\]]         }}},
    {{ "//a/b/c/d"    }, {{ [[\\a\b\c]], [[\\a\b\]]      }}},
  },
  drive = {
    "common",
    {{ ""          }, { ""        }},
    {{ "/a/b"      }, { ""        }},
    {{ "a/b"       }, { ""        }},
    "windows",
    {{ "./c:a"     }, { ""        }},
    {{ "c:"        }, { "c:"      }},
    {{ "c:a/b"     }, { "c:"      }},
    {{ "c:/"       }, { "c:"      }},
    {{ "c:/a/b/"   }, { "c:"      }},
    {{ "//a/b"     }, { [[\\a\b]] }},
    {{ "//a/b/"    }, { [[\\a\b]] }},
    {{ "//a/b/c/d" }, { [[\\a\b]] }},
  },
  is_relative_to = {
    "common",
    {{ "a/b"                   , ""                       }, { true  }},
    {{ "a/b"                   , "a/"                     }, { true  }},
    {{ "a/b"                   , "a"                      }, { true  }},
    {{ "a/b"                   , "a/b"                    }, { true  }},
    {{ "a/b"                   , "a/b/"                   }, { true  }},
    {{ "a/b"                   , "c"                      }, { false }},
    {{ "a/b"                   , "a/b/c"                  }, { false }},
    {{ "a/b"                   , "a/c"                    }, { false }},
    {{ "a/b"                   , "/a"                     }, { false }},
    {{ "/a/b"                  , "/"                      }, { true  }},
    {{ "/a/b"                  , "/a"                     }, { true  }},
    {{ "/a/b"                  , "/a/"                    }, { true  }},
    {{ "/a/b"                  , "/a/b"                   }, { true  }},
    {{ "/a/b"                  , "/a/b/"                  }, { true  }},
    {{ "/a/b"                  , "/c"                     }, { false }},
    {{ "/a/b"                  , "/a/b/c"                 }, { false }},
    {{ "/a/b"                  , "/a/c"                   }, { false }},
    {{ "/a/b"                  , ""                       }, { false }},
    {{ "/a/b"                  , "a"                      }, { false }},
    "windows",
    {{ "C:Foo/Bar"             , "c:"                     }, { true  }},
    {{ "C:Foo/Bar"             , "c:foO"                  }, { true  }},
    {{ "C:Foo/Bar"             , "c:foO/"                 }, { true  }},
    {{ "C:Foo/Bar"             , "c:foO/baR"              }, { true  }},
    {{ "C:Foo/Bar"             , ""                       }, { false }},
    {{ "C:Foo/Bar"             , "d:"                     }, { false }},
    {{ "C:Foo/Bar"             , "/"                      }, { false }},
    {{ "C:Foo/Bar"             , "Foo"                    }, { false }},
    {{ "C:Foo/Bar"             , "/Foo"                   }, { false }},
    {{ "C:Foo/Bar"             , "C:/Foo"                 }, { false }},
    {{ "C:Foo/Bar"             , "C:Foo/Bar/Baz"          }, { false }},
    {{ "C:Foo/Bar"             , "C:Foo/Baz"              }, { false }},
    {{ "C:/Foo/Bar"            , "c:/"                    }, { true  }},
    {{ "C:/Foo/Bar"            , "c:/foO"                 }, { true  }},
    {{ "C:/Foo/Bar"            , "c:/foO/"                }, { true  }},
    {{ "C:/Foo/Bar"            , "c:/foO/baR"             }, { true  }},
    {{ "C:/Foo/Bar"            , "c:"                     }, { false }},
    {{ "C:/Foo/Bar"            , "C:/Baz"                 }, { false }},
    {{ "C:/Foo/Bar"            , "C:/Foo/Bar/Baz"         }, { false }},
    {{ "C:/Foo/Bar"            , "C:/Foo/Baz"             }, { false }},
    {{ "C:/Foo/Bar"            , "C:Foo"                  }, { false }},
    {{ "C:/Foo/Bar"            , "d:"                     }, { false }},
    {{ "C:/Foo/Bar"            , "d:/"                    }, { false }},
    {{ "C:/Foo/Bar"            , "/"                      }, { false }},
    {{ "C:/Foo/Bar"            , "/Foo"                   }, { false }},
    {{ "C:/Foo/Bar"            , "//C/Foo"                }, { false }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare"         }, { true  }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/"        }, { true  }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo"     }, { true  }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo/"    }, { true  }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo/Bar" }, { true  }},
    {{ "//Server/Share/Foo/Bar", "/Server/Share/Foo"      }, { false }},
    {{ "//Server/Share/Foo/Bar", "c:/Server/Share/Foo"    }, { false }},
    {{ "//Server/Share/Foo/Bar", "//z/Share/Foo"          }, { false }},
    {{ "//Server/Share/Foo/Bar", "//Server/z/Foo"         }, { false }},
  },
  match = {
    "common",
    {{ "b.lua"               , "b.lua"                      }, { true  }},
    {{ "a/b.lua"             , "b.lua"                      }, { true  }},
    {{ "/a/b.lua"            , "b.lua"                      }, { true  }},
    {{ "a.lua"               , "b.lua"                      }, { false }},
    {{ "b/lua"               , "b.lua"                      }, { false }},
    {{ "/a.lua"              , "b.lua"                      }, { false }},
    {{ "b.lua/c"             , "b.lua"                      }, { false }},
    {{ "b.lua"               , "*.lua"                      }, { true  }},
    {{ "a/b.lua"             , "*.lua"                      }, { true  }},
    {{ "/a/b.lua"            , "*.lua"                      }, { true  }},
    {{ "file.txt"            , "file.txt"                   }, { true  }},
    {{ "fileXtxt"            , "file.txt"                   }, { false }},
    {{ "file1.txt"           , "file?.txt"                  }, { true  }},
    {{ "file10.txt"          , "file?.txt"                  }, { false }},
    {{ "notes.txt"           , "n?tes.*"                    }, { true  }},
    {{ "a+b"                 , "a+b"                        }, { true  }},
    {{ "ab"                  , "a+b"                        }, { false }},
    {{ "foo[bar]"            , "foo[bar]"                   }, { true  }},
    {{ "foob"                , "foo[bar]"                   }, { false }},
    {{ "a(b)"                , "a(b)"                       }, { true  }},
    {{ "ab"                  , "a(b)"                       }, { false }},
    {{ "^abc"                , "^abc"                       }, { true  }},
    {{ "abc"                 , "^abc"                       }, { false }},
    {{ "abc$"                , "abc$"                       }, { true  }},
    {{ "abc"                 , "abc$"                       }, { false }},
    {{ "b.luac"              , "*.lua"                      }, { false }},
    {{ "b./lua"              , "*.lua"                      }, { false }},
    {{ "b.lua/c"             , "*.lua"                      }, { false }},
    {{ "ab/c.lua"            , "a*/*.lua"                   }, { true  }},
    {{ "/d/ab/c.lua"         , "a*/*.lua"                   }, { true  }},
    {{ "a.lua"               , "a*/*.lua"                   }, { false }},
    {{ "/dab/c.lua"          , "a*/*.lua"                   }, { false }},
    {{ "ab/c.lua/d"          , "a*/*.lua"                   }, { false }},
    {{ "/b.lua"              , "/*.lua"                     }, { true  }},
    {{ "b.lua"               , "/*.lua"                     }, { false }},
    {{ "a/b.lua"             , "/*.lua"                     }, { false }},
    {{ "/a/b.lua"            , "/*.lua"                     }, { false }},
    {{ "/a/b.lua"            , "/a/*.lua"                   }, { true  }},
    {{ "/ab.lua"             , "/a/*.lua"                   }, { false }},
    {{ "/a/b/c.lua"          , "/a/*.lua"                   }, { false }},
    {{ "/a/b/c.lua"          , "/**/*.lua"                  }, { false }},
    {{ "/a/b/c.lua"          , "/a/**/*.lua"                }, { true  }},
    {{ "A.lua"               , "a.LUA"              , true  }, { false }},
    {{ "A.lua"               , "a.LUA"              , false }, { true  }},
    {{ "/a/b/c.lua"          , "/A/*/*.Lua"         , false }, { true  }},
    {{ ""                    , "*"                          }, { false }},
    {{ ""                    , "**"                         }, { false }},
    {{ ""                    , "**/*"                       }, { false }},
    {{ ""                    , "."                          }, { false }},
    {{ "a/b"                 , ""                           }, { false }},
    "posix",
    {{ "A.lua"               , "a.LUA"                      }, { false }},
    {{ "a.lua"               , "a.lua"                      }, { true  }},
    "windows",
    {{ "c:/b.lua"            , "*:/*.lua"                   }, { true  }},
    {{ "c:/b.lua"            , "c:/*.lua"                   }, { true  }},
    {{ "d:/b.lua"            , "c:/*.lua"                   }, { false }},
    {{ "b.lua"               , "c:*.lua"                    }, { false }},
    {{ "b.lua"               , "c:/*.lua"                   }, { false }},
    {{ "c:b.lua"             , "/*.lua"                     }, { false }},
    {{ "c:b.lua"             , "c:/*.lua"                   }, { false }},
    {{ "/b.lua"              , "c:*.lua"                    }, { false }},
    {{ "/b.lua"              , "c:/*.lua"                   }, { false }},
    {{ "//some/share/a.lua"  , "//*/*/*.lua"                }, { true  }},
    {{ "//some/share/a.lua"  , "//some/share/*.lua"         }, { true  }},
    {{ "//other/share/a.lua" , "//some/share/*.lua"         }, { false }},
    {{ "//some/share/a/b.lua", "//some/share/*.lua"         }, { false }},
    {{ "B.lua"               , "b.LUA"                      }, { true  }},
    {{ "c:/a/B.Lua"          , "C:/A/*.lUA"         , true  }, { false }},
    {{ "c:/a/B.Lua"          , "C:/A/*.lUA"                 }, { true  }},
    {{ "//Some/Share/B.Lua"  , "//somE/sharE/*.lUA"         }, { true  }},
    {{ "c:/b.lua"            , "/*.lua"                     }, { false }},
    {{ "c:/b.lua"            , "c:*.lua"                    }, { false }},
    {{ "//some/share/a.lua"  , "/*.lua"                     }, { false }},
    {{ [[c:\]]               , [[c:\]]                      }, { true  }},
    {{ [[c:]]                , [[c:]]                       }, { true  }},
    {{ [[\\Server\Share]]    , [[\\Server\Share]]           }, { true  }},
  },
  parts = {
    "common",
    {{ "a/b.txt"     }, {{ "a"       , "b.txt"      }}},
    {{ "a/b"         }, {{ "a"       , "b"          }}},
    "posix",
    {{ "/a/b"        }, {{ "/"       , "a"    , "b" }}},
    "windows",
    {{ "/a/b"        }, {{ [[\]]     , "a"    , "b" }}},
    {{ [[a\b]]       }, {{ "a"       , "b"          }}},
    {{ [[\a\b]]      }, {{ [[\]]     , "a"    , "b" }}},
    {{ [[c:a\b]]     }, {{ "c:"      , "a"    , "b" }}},
    {{ [[c:\a\b]]    }, {{ [[c:\]]   , "a"    , "b" }}},
    {{ [[\\a\b\c\d]] }, {{ [[\\a\b\]], "c"    , "d" }}},
  },
  relative_to = {
    "posix",
    {{ "a/b"                   , ""                             }, { "a/b"                                                                          }},
    {{ "a/b"                   , "a"                            }, { "b"                                                                            }},
    {{ "a/b"                   , "a/"                           }, { "b"                                                                            }},
    {{ "a"                     , "a"                            }, { "."                                                                            }},
    {{ "a/b"                   , ""                      , true }, { "a/b"                                                                          }},
    {{ "a/b"                   , "a"                     , true }, { "b"                                                                            }},
    {{ "a/b"                   , "a/"                    , true }, { "b"                                                                            }},
    {{ "a/b"                   , "a/b"                   , true }, { "."                                                                            }},
    {{ "a"                     , "a"                     , true }, { "."                                                                            }},
    {{ "a/b"                   , "a/c"                   , true }, { "../b"                                                                         }},
    {{ "a/b"                   , "a/b/c"                 , true }, { ".."                                                                           }},
    {{ "a/b"                   , "c"                     , true }, { "../a/b"                                                                       }},
    {{ "a/b"                   , "c"                            }, { nil, "'a/b' is not in the subpath of 'c'"                                      }},
    {{ "a/b"                   , "a/b/c"                        }, { nil, "'a/b' is not in the subpath of 'a/b/c'"                                  }},
    {{ "a/b"                   , "a/c"                          }, { nil, "'a/b' is not in the subpath of 'a/c'"                                    }},
    {{ "a/b"                   , "/a"                           }, { nil, "'a/b' is not in the subpath of '/a'"                                     }},
    {{ "a/b"                   , "../a"                         }, { nil, "'a/b' is not in the subpath of '../a'"                                   }},
    {{ "a/b"                   , "a/.."                         }, { nil, "'a/b' is not in the subpath of 'a/..'"                                   }},
    {{ "a/b"                   , "/a/.."                        }, { nil, "'a/b' is not in the subpath of '/a/..'"                                  }},
    {{ "a/b"                   , "/"                     , true }, { nil, "'a/b' is not in the subpath of '/'"                                      }},
    {{ "a/b"                   , "/a"                    , true }, { nil, "'a/b' is not in the subpath of '/a'"                                     }},
    {{ "a/b"                   , "../a"                  , true }, { "../../a/b"                                                                    }},
    {{ "a/b"                   , "a/.."                  , true }, { "../b"                                                                         }},
    {{ "a/b"                   , "/a/.."                 , true }, { nil, "'a/b' is not in the subpath of '/a/..'"                                  }},
    {{ "/a/b"                  , "/"                            }, { "a/b"                                                                          }},
    {{ "/a/b"                  , "/a"                           }, { "b"                                                                            }},
    {{ "/a/b"                  , "/a/"                          }, { "b"                                                                            }},
    {{ "/a/b"                  , "/a/b"                         }, { "."                                                                            }},
    {{ "/a/b"                  , "/"                     , true }, { "a/b"                                                                          }},
    {{ "/a/b"                  , "/a"                    , true }, { "b"                                                                            }},
    {{ "/a/b"                  , "/a/"                   , true }, { "b"                                                                            }},
    {{ "/a/b"                  , "/a/b"                  , true }, { "."                                                                            }},
    {{ "/a/b"                  , "/a/c"                  , true }, { "../b"                                                                         }},
    {{ "/a/b"                  , "/a/b/c"                , true }, { ".."                                                                           }},
    {{ "/a/b"                  , "/c"                    , true }, { "../a/b"                                                                       }},
    {{ "/a/b"                  , "/c"                           }, { nil, "'/a/b' is not in the subpath of '/c'"                                    }},
    {{ "/a/b"                  , "/a/b/c"                       }, { nil, "'/a/b' is not in the subpath of '/a/b/c'"                                }},
    {{ "/a/b"                  , "/a/c"                         }, { nil, "'/a/b' is not in the subpath of '/a/c'"                                  }},
    {{ "/a/b"                  , ""                             }, { nil, "'/a/b' is not in the subpath of ''"                                      }},
    {{ "/a/b"                  , "a"                            }, { nil, "'/a/b' is not in the subpath of 'a'"                                     }},
    {{ "/a/b"                  , "../a"                         }, { nil, "'/a/b' is not in the subpath of '../a'"                                  }},
    {{ "/a/b"                  , "a/.."                         }, { nil, "'/a/b' is not in the subpath of 'a/..'"                                  }},
    {{ "/a/b"                  , "/a/.."                        }, { nil, "'/a/b' is not in the subpath of '/a/..'"                                 }},
    {{ "/a/b"                  , ""                      , true }, { nil, "'/a/b' is not in the subpath of ''"                                      }},
    {{ "/a/b"                  , "a"                     , true }, { nil, "'/a/b' is not in the subpath of 'a'"                                     }},
    {{ "/a/b"                  , "../a"                  , true }, { nil, "'/a/b' is not in the subpath of '../a'"                                  }},
    {{ "/a/b"                  , "a/.."                  , true }, { nil, "'/a/b' is not in the subpath of 'a/..'"                                  }},
    {{ "/a/b"                  , "/a/.."                 , true }, { "../b"                                                                         }},
    "windows",
    {{ "C:Foo/Bar"             , "c:"                           }, { [[Foo\Bar]]                                                                    }},
    {{ "C:Foo/Bar"             , "c:foO"                        }, { "Bar"                                                                          }},
    {{ "C:Foo/Bar"             , "c:foO/"                       }, { "Bar"                                                                          }},
    {{ "C:Foo/Bar"             , "c:foO/baR"                    }, { "."                                                                            }},
    {{ "C:Foo/Bar"             , "c:"                    , true }, { [[Foo\Bar]]                                                                    }},
    {{ "C:Foo/Bar"             , "c:foO"                 , true }, { "Bar"                                                                          }},
    {{ "C:Foo/Bar"             , "c:foO/"                , true }, { "Bar"                                                                          }},
    {{ "C:Foo/Bar"             , "c:foO/baR"             , true }, { "."                                                                            }},
    {{ "C:Foo/Bar"             , "C:Foo/Bar/Baz"         , true }, { ".."                                                                           }},
    {{ "C:Foo/Bar"             , "C:Foo/Baz"             , true }, { [[..\Bar]]                                                                     }},
    {{ "C:Foo/Bar"             , "C:Baz/Bar"             , true }, { [[..\..\Foo\Bar]]                                                              }},
    {{ "C:Foo/Bar"             , ""                             }, { nil, "'C:Foo/Bar' is not in the subpath of ''"                                 }},
    {{ "C:Foo/Bar"             , "d:"                           }, { nil, "'C:Foo/Bar' is not in the subpath of 'd:'"                               }},
    {{ "C:Foo/Bar"             , "/"                            }, { nil, "'C:Foo/Bar' is not in the subpath of '/'"                                }},
    {{ "C:Foo/Bar"             , "Foo"                          }, { nil, "'C:Foo/Bar' is not in the subpath of 'Foo'"                              }},
    {{ "C:Foo/Bar"             , "/Foo"                         }, { nil, "'C:Foo/Bar' is not in the subpath of '/Foo'"                             }},
    {{ "C:Foo/Bar"             , "C:/Foo"                       }, { nil, "'C:Foo/Bar' is not in the subpath of 'C:/Foo'"                           }},
    {{ "C:Foo/Bar"             , "C:Foo/Bar/Baz"                }, { nil, "'C:Foo/Bar' is not in the subpath of 'C:Foo/Bar/Baz'"                    }},
    {{ "C:Foo/Bar"             , "C:Foo/Baz"                    }, { nil, "'C:Foo/Bar' is not in the subpath of 'C:Foo/Baz'"                        }},
    {{ "C:Foo/Bar"             , ""                      , true }, { nil, "'C:Foo/Bar' is not in the subpath of ''"                                 }},
    {{ "C:Foo/Bar"             , "d:"                    , true }, { nil, "'C:Foo/Bar' is not in the subpath of 'd:'"                               }},
    {{ "C:Foo/Bar"             , "/"                     , true }, { nil, "'C:Foo/Bar' is not in the subpath of '/'"                                }},
    {{ "C:Foo/Bar"             , "Foo"                   , true }, { nil, "'C:Foo/Bar' is not in the subpath of 'Foo'"                              }},
    {{ "C:Foo/Bar"             , "/Foo"                  , true }, { nil, "'C:Foo/Bar' is not in the subpath of '/Foo'"                             }},
    {{ "C:Foo/Bar"             , "C:/Foo"                , true }, { nil, "'C:Foo/Bar' is not in the subpath of 'C:/Foo'"                           }},
    {{ "C:/Foo/Bar"            , "c:/"                          }, { [[Foo\Bar]]                                                                    }},
    {{ "C:/Foo/Bar"            , "c:/foO"                       }, { "Bar"                                                                          }},
    {{ "C:/Foo/Bar"            , "c:/foO/"                      }, { "Bar"                                                                          }},
    {{ "C:/Foo/Bar"            , "c:/foO/baR"                   }, { "."                                                                            }},
    {{ "C:/Foo/Bar"            , "c:/"                   , true }, { [[Foo\Bar]]                                                                    }},
    {{ "C:/Foo/Bar"            , "c:/foO"                , true }, { "Bar"                                                                          }},
    {{ "C:/Foo/Bar"            , "c:/foO/"               , true }, { "Bar"                                                                          }},
    {{ "C:/Foo/Bar"            , "c:/foO/baR"            , true }, { "."                                                                            }},
    {{ "C:/Foo/Bar"            , "C:/Baz"                , true }, { [[..\Foo\Bar]]                                                                 }},
    {{ "C:/Foo/Bar"            , "C:/Foo/Bar/Baz"        , true }, { ".."                                                                           }},
    {{ "C:/Foo/Bar"            , "C:/Foo/Baz"            , true }, { [[..\Bar]]                                                                     }},
    {{ "C:/Foo/Bar"            , "c:"                           }, { nil, "'C:/Foo/Bar' is not in the subpath of 'c:'"                              }},
    {{ "C:/Foo/Bar"            , "C:/Baz"                       }, { nil, "'C:/Foo/Bar' is not in the subpath of 'C:/Baz'"                          }},
    {{ "C:/Foo/Bar"            , "C:/Foo/Bar/Baz"               }, { nil, "'C:/Foo/Bar' is not in the subpath of 'C:/Foo/Bar/Baz'"                  }},
    {{ "C:/Foo/Bar"            , "C:/Foo/Baz"                   }, { nil, "'C:/Foo/Bar' is not in the subpath of 'C:/Foo/Baz'"                      }},
    {{ "C:/Foo/Bar"            , "C:Foo"                        }, { nil, "'C:/Foo/Bar' is not in the subpath of 'C:Foo'"                           }},
    {{ "C:/Foo/Bar"            , "d:"                           }, { nil, "'C:/Foo/Bar' is not in the subpath of 'd:'"                              }},
    {{ "C:/Foo/Bar"            , "d:/"                          }, { nil, "'C:/Foo/Bar' is not in the subpath of 'd:/'"                             }},
    {{ "C:/Foo/Bar"            , "/"                            }, { nil, "'C:/Foo/Bar' is not in the subpath of '/'"                               }},
    {{ "C:/Foo/Bar"            , "/Foo"                         }, { nil, "'C:/Foo/Bar' is not in the subpath of '/Foo'"                            }},
    {{ "C:/Foo/Bar"            , "//C/Foo"                      }, { nil, "'C:/Foo/Bar' is not in the subpath of '//C/Foo'"                         }},
    {{ "C:/Foo/Bar"            , "c:"                    , true }, { nil, "'C:/Foo/Bar' is not in the subpath of 'c:'"                              }},
    {{ "C:/Foo/Bar"            , "C:Foo"                 , true }, { nil, "'C:/Foo/Bar' is not in the subpath of 'C:Foo'"                           }},
    {{ "C:/Foo/Bar"            , "d:"                    , true }, { nil, "'C:/Foo/Bar' is not in the subpath of 'd:'"                              }},
    {{ "C:/Foo/Bar"            , "d:/"                   , true }, { nil, "'C:/Foo/Bar' is not in the subpath of 'd:/'"                             }},
    {{ "C:/Foo/Bar"            , "/"                     , true }, { nil, "'C:/Foo/Bar' is not in the subpath of '/'"                               }},
    {{ "C:/Foo/Bar"            , "/Foo"                  , true }, { nil, "'C:/Foo/Bar' is not in the subpath of '/Foo'"                            }},
    {{ "C:/Foo/Bar"            , "//C/Foo"               , true }, { nil, "'C:/Foo/Bar' is not in the subpath of '//C/Foo'"                         }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare"               }, { [[Foo\Bar]]                                                                    }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/"              }, { [[Foo\Bar]]                                                                    }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo"           }, { "Bar"                                                                          }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo/"          }, { "Bar"                                                                          }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo/Bar"       }, { "."                                                                            }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare"        , true }, { [[Foo\Bar]]                                                                    }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/"       , true }, { [[Foo\Bar]]                                                                    }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo"    , true }, { "Bar"                                                                          }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo/"   , true }, { "Bar"                                                                          }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/Foo/Bar", true }, { "."                                                                            }},
    {{ "//Server/Share/Foo/Bar", "//sErver/sHare/bar"    , true }, { [[..\Foo\Bar]]                                                                 }},
    {{ "//Server/Share/Foo/Bar", "/Server/Share/Foo"            }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of '/Server/Share/Foo'"   }},
    {{ "//Server/Share/Foo/Bar", "c:/Server/Share/Foo"          }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of 'c:/Server/Share/Foo'" }},
    {{ "//Server/Share/Foo/Bar", "//z/Share/Foo"                }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of '//z/Share/Foo'"       }},
    {{ "//Server/Share/Foo/Bar", "//Server/z/Foo"               }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of '//Server/z/Foo'"      }},
    {{ "//Server/Share/Foo/Bar", "/Server/Share/Foo"     , true }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of '/Server/Share/Foo'"   }},
    {{ "//Server/Share/Foo/Bar", "c:/Server/Share/Foo"   , true }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of 'c:/Server/Share/Foo'" }},
    {{ "//Server/Share/Foo/Bar", "//z/Share/Foo"         , true }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of '//z/Share/Foo'"       }},
    {{ "//Server/Share/Foo/Bar", "//Server/z/Foo"        , true }, { nil, "'//Server/Share/Foo/Bar' is not in the subpath of '//Server/z/Foo'"      }},
  },
  with_name = {
    "common",
    {{ ""                    , "d.xml"       }, { nil, "'' has an empty name"             }},
    {{ "."                   , "d.xml"       }, { nil, "'.' has an empty name"            }},
    {{ "/"                   , "d.xml"       }, { nil, "'/' has an empty name"            }},
    {{ "a/b"                 , ""            }, { nil, "invalid name ''"                  }},
    {{ "a/b"                 , "."           }, { nil, "invalid name '.'"                 }},
    {{ "a"                   , "b/c"         }, { nil, "invalid name 'b/c'"               }},
    {{ "a/b"                 , "/c"          }, { nil, "invalid name '/c'"                }},
    {{ "a/b"                 , "c/"          }, { nil, "invalid name 'c/'"                }},
    {{ "a/b"                 , "c/d"         }, { nil, "invalid name 'c/d'"               }},
    "posix",
    {{ "a/b"                , "d.xml"        }, { "a/d.xml"                               }},
    {{ "/a/b"               , "d.xml"        }, { "/a/d.xml"                              }},
    {{ "a/b.lua"            , "d.xml"        }, { "a/d.xml"                               }},
    {{ "/a/b.lua"           , "d.xml"        }, { "/a/d.xml"                              }},
    {{ "a/Dot ending."      , "d.xml"        }, { "a/d.xml"                               }},
    {{ "/a/Dot ending."     , "d.xml"        }, { "/a/d.xml"                              }},
    "windows",
    {{ [[c:a\b]]            , "d.xml"        }, { [[c:a\d.xml]]                           }},
    {{ [[c:\a\b]]           , "d.xml"        }, { [[c:\a\d.xml]]                          }},
    {{ [[c:a\Dot ending.]]  , "d.xml"        }, { [[c:a\d.xml]]                           }},
    {{ [[c:\a\Dot ending.]] , "d.xml"        }, { [[c:\a\d.xml]]                          }},
    {{ "a"                  , "d:"           }, { [[.\d:]]                                }},
    {{ "a"                  , "d:e"          }, { [[.\d:e]]                               }},
    {{ [[c:a\b]]            , "d:"           }, { [[c:a\d:]]                              }},
    {{ [[c:a\b]]            , "d:e"          }, { [[c:a\d:e]]                             }},
    {{ "a"                  , "file"         }, { "file"                                  }},
    {{ "a"                  , "file.txt"     }, { "file.txt"                              }},
    {{ [[c:a\b]]            , [[d:\e]]       }, { nil, [[invalid name 'd:\e']]            }},
    {{ [[c:a\b]]            , [[\\My\Share]] }, { nil, [[invalid name '\\My\Share']]      }},
    {{ "c:"                 , "d.xml"        }, { nil, [['c:' has an empty name]]         }},
    {{ [[c:\]]              , "d.xml"        }, { nil, [['c:\' has an empty name]]        }},
    {{ [[\\My\Share]]       , "d.xml"        }, { nil, [['\\My\Share' has an empty name]] }},
  },
  with_stem = {
    "common",
    {{ "a/b"              , ""     }, { nil, "'a/b' has an empty stem"         }},
    {{ "foo.gz"           , ""     }, { nil, "'foo.gz' has an empty stem"      }},
    {{ "/a/b/foo.gz"      , ""     }, { nil, "'/a/b/foo.gz' has an empty stem" }},
    {{ "a/b"              , "/c"   }, { nil, "invalid name '/c'"               }},
    {{ "a/b"              , "c/"   }, { nil, "invalid name 'c/'"               }},
    {{ "a/b"              , "c/d"  }, { nil, "invalid name 'c/d'"              }},
    {{ ""                 , "d"    }, { nil, "'' has an empty name"            }},
    {{ "."                , "d"    }, { nil, "'.' has an empty name"           }},
    {{ "/"                , "d"    }, { nil, "'/' has an empty name"           }},
    {{ "a/b"              , ""     }, { nil, "'a/b' has an empty stem"         }},
    {{ "a/b"              , "."    }, { nil, "invalid name '.'"                }},
    "posix",
    {{ "a/b"              , "d"    }, { "a/d"                                  }},
    {{ "/a/b"             , "d"    }, { "/a/d"                                 }},
    {{ "a/b.lua"          , "d"    }, { "a/d.lua"                              }},
    {{ "/a/b.lua"         , "d"    }, { "/a/d.lua"                             }},
    {{ "/a/b.tar.gz"      , "d"    }, { "/a/d.gz"                              }},
    {{ "a/b.txt/"         , "c"    }, { "a/c.txt"                              }},
    {{ "a/Dot ending."    , "d"    }, { "a/d."                                 }},
    {{ "/a/Dot ending."   , "d"    }, { "/a/d."                                }},
    "windows",
    {{ "c:a/b"            , "d"    }, { [[c:a\d]]                              }},
    {{ "c:/a/b"           , "d"    }, { [[c:\a\d]]                             }},
    {{ "c:a/Dot ending."  , "d"    }, { [[c:a\d.]]                             }},
    {{ "c:/a/Dot ending." , "d"    }, { [[c:\a\d.]]                            }},
    {{ "a"                , "d:"   }, { [[.\d:]]                               }},
    {{ "a"                , "d:e"  }, { [[.\d:e]]                              }},
    {{ "c:a/b"            , "d:"   }, { [[c:a\d:]]                             }},
    {{ "c:a/b"            , "d:e"  }, { [[c:a\d:e]]                            }},
    {{ "c:a/b"            , "d:/e" }, { nil, "invalid name 'd:/e'"             }},
    {{ "c:a/b"            , "//d"  }, { nil, "invalid name '//d'"              }},
    {{ "c:"               , "d"    }, { nil, "'c:' has an empty name"          }},
    {{ "c:/"              , "d"    }, { nil, "'c:/' has an empty name"         }},
    {{ "//My/Share"       , "d"    }, { nil, "'//My/Share' has an empty name"  }},
  },
  with_suffix = {
    "common",
    {{ ""          , ".gz"    }, { nil, "'' has an empty name"      }},
    {{ "/"         , ".gz"    }, { nil, "'/' has an empty name"     }},
    {{ "a/b"       , "gz"     }, { nil, "invalid suffix 'gz'"       }},
    {{ "a/b"       , "/"      }, { nil, "invalid suffix '/'"        }},
    {{ "a/b"       , "/.gz"   }, { nil, "invalid suffix '/.gz'"     }},
    {{ "a/b"       , "c/d"    }, { nil, "invalid suffix 'c/d'"      }},
    {{ "a/b"       , ".c/.d"  }, { nil, "invalid name 'b.c/.d'"     }},
    {{ "a/b"       , "./.d"   }, { nil, "invalid name 'b./.d'"      }},
    {{ "a/b"       , ".d/."   }, { nil, "invalid name 'b.d/.'"      }},
    "posix",
    {{ "a/b"       , ".gz"    }, { "a/b.gz"                         }},
    {{ "/a/b"      , ".gz"    }, { "/a/b.gz"                        }},
    {{ "a/b.lua"   , ".gz"    }, { "a/b.gz"                         }},
    {{ "/a/b.lua"  , ".gz"    }, { "/a/b.gz"                        }},
    {{ "a/b.lua"   , ""       }, { "a/b"                            }},
    {{ "/a/b"      , ""       }, { "/a/b"                           }},
    {{ "a/b"       , "."      }, { "a/b."                           }},
    {{ "/a/b"      , "."      }, { "/a/b."                          }},
    {{ "a/b.lua"   , "."      }, { "a/b."                           }},
    {{ "/a/b.lua"  , "."      }, { "/a/b."                          }},
    "windows",
    {{ "a/b"       , ".gz"    }, { [[a\b.gz]]                       }},
    {{ "a/b.lua"   , ".gz"    }, { [[a\b.gz]]                       }},
    {{ "a/b.lua"   , ""       }, { [[a\b]]                          }},
    {{ "a/b"       , "."      }, { [[a\b.]]                         }},
    {{ "a/b.lua"   , "."      }, { [[a\b.]]                         }},
    {{ "c:a/b"     , ".gz"    }, { [[c:a\b.gz]]                     }},
    {{ "c:/a/b"    , ".gz"    }, { [[c:\a\b.gz]]                    }},
    {{ "c:a/b.lua" , ".gz"    }, { [[c:a\b.gz]]                     }},
    {{ "c:/a/b.lua", ".gz"    }, { [[c:\a\b.gz]]                    }},
    {{ "//a/b"     , ".gz"    }, { nil, "'//a/b' has an empty name" }},
    {{ "c:a/b"     , "gz"     }, { nil, "invalid suffix 'gz'"       }},
    {{ "c:a/b"     , "/"      }, { nil, "invalid suffix '/'"        }},
    {{ "c:a/b"     , [[\]]    }, { nil, [[invalid suffix '\']]      }},
    {{ "c:a/b"     , "c:"     }, { nil, "invalid suffix 'c:'"       }},
    {{ "c:a/b"     , "/.gz"   }, { nil, "invalid suffix '/.gz'"     }},
    {{ "c:a/b"     , [[\.gz]] }, { nil, [[invalid suffix '\.gz']]   }},
    {{ "c:a/b"     , "c:.gz"  }, { nil, "invalid suffix 'c:.gz'"    }},
    {{ "c:a/b"     , "c/d"    }, { nil, "invalid suffix 'c/d'"      }},
    {{ "c:a/b"     , [[c\d]]  }, { nil, [[invalid suffix 'c\d']]    }},
    {{ "c:a/b"     , ".c/d"   }, { nil, "invalid name 'b.c/d'"      }},
    {{ "c:a/b"     , [[.c\d]] }, { nil, [[invalid name 'b.c\d']]    }},
  },
  root = {
    "common",
    {{ ""          }, { ""    }},
    {{ "a/b"       }, { ""    }},
    "posix",
    {{ "/"         }, { "/"   }},
    {{ "/a/b"      }, { "/"   }},
    {{ "//a/b"     }, { "//"  }},
    "windows",
    {{ "/"         }, { [[\]] }},
    {{ "/a/b"      }, { [[\]] }},
    {{ "c:"        }, { ""    }},
    {{ "c:a/b"     }, { ""    }},
    {{ "c:/"       }, { [[\]] }},
    {{ "c:/a/b/"   }, { [[\]] }},
    {{ "//a/b"     }, { [[\]] }},
    {{ "//a/b/"    }, { [[\]] }},
    {{ "//a/b/c"   }, { [[\]] }},
    {{ "//a/b/c/d" }, { [[\]] }},
    {{ [[\\a\b]]   }, { [[\]] }},
  },
  join = {
    "posix",
    {{ "//a"              , "b"                }, { "//a/b"                       }},
    {{ "/a"               , "//c"              }, { "//c"                         }},
    {{ "//a"              , "/c"               }, { "/c"                          }},
    "windows",
    {{ "C:/a"             , "b"                }, { [[C:/a\b]]                    }},
    {{ "C:/a/b"           , "x/y"              }, { [[C:/a/b\x/y]]                }},
    {{ "C:/a/b"           , "/x/y"             }, { "C:/x/y"                      }},
    {{ "C:/a/b"           , "D:x/y"            }, { "D:x/y"                       }},
    {{ "C:/a/b"           , "D:/x/y"           }, { "D:/x/y"                      }},
    {{ "C:/a/b"           , "//host/share/x/y" }, { "//host/share/x/y"            }},
    {{ "C:/a/b"           , "c:x/y"            }, { [[c:/a/b\x/y]]                }},
    {{ "C:/a/b"           , "c:/x/y"           }, { "c:/x/y"                      }},
    {{ "C:/a/b"           , "./d:s"            }, { [[C:/a/b\./d:s]]              }},
    {{ "C:/a/b"           , "./dd:s"           }, { [[C:/a/b\./dd:s]]             }},
    {{ "C:/a/b"           , "E:d:s"            }, { "E:d:s"                       }},
    {{ "//server"         , "share"            }, { [[//server\share]]            }},
    {{ "//./BootPartition", "Windows"          }, { [[//./BootPartition\Windows]] }},
  },
  stem = {
    "common",
    {{ ""                  }, { ""             }},
    {{ "."                 }, { ""             }},
    {{ ".."                }, { ".."           }},
    {{ "a/b.tar.gz"        }, { "b.tar"        }},
    {{ "/"                 }, { ""             }},
    {{ "a/b"               }, { "b"            }},
    {{ "a/b.lua"           }, { "b"            }},
    {{ "a/.hgrc"           }, { ".hgrc"        }},
    {{ "a/.hg.rc"          }, { ".hg"          }},
    {{ "archive.tar.gz"    }, { "archive.tar"  }},
    {{ ".bashrc"           }, { ".bashrc"      }},
    {{ "a/trailing.dot."   }, { "trailing.dot" }},
    {{ "a/..d.o.t.."       }, { "..d.o.t."     }},
    {{ "a/inn.er..dots"    }, { "inn.er."      }},
    {{ "photo"             }, { "photo"        }},
    {{ "photo.jpg"         }, { "photo"        }},
    "windows",
    {{ "c:"                }, { ""             }},
    {{ "c:.."              }, { ".."           }},
    {{ "c:/"               }, { ""             }},
    {{ "c:a/b"             }, { "b"            }},
    {{ "c:a/b.lua"         }, { "b"            }},
    {{ "c:a/.hgrc"         }, { ".hgrc"        }},
    {{ "c:a/.hg.rc"        }, { ".hg"          }},
    {{ "c:a/b.tar.gz"      }, { "b.tar"        }},
    {{ "c:a/trailing.dot." }, { "trailing.dot" }},
  },
  suffixes = {
    "common",
    {{ ""                       }, {{                      }}},
    {{ "."                      }, {{                      }}},
    {{ "/"                      }, {{                      }}},
    {{ "a/b"                    }, {{                      }}},
    {{ "a/..d.o.t.."            }, {{ ".o", ".t", ".", "." }}},
    {{ "/a/b"                   }, {{                      }}},
    {{ "/a/b/."                 }, {{                      }}},
    {{ "a/b.lua"                }, {{ ".lua"               }}},
    {{ "a/b.lua/"               }, {{ ".lua"               }}},
    {{ "/a/b.lua"               }, {{ ".lua"               }}},
    {{ "a/.hgrc"                }, {{                      }}},
    {{ "a/inn.er..dots"         }, {{ ".er", ".", ".dots"  }}},
    {{ "/a/.hgrc"               }, {{                      }}},
    {{ "a/.hg.rc"               }, {{ ".rc"                }}},
    {{ "/a/.hg.rc"              }, {{ ".rc"                }}},
    {{ "a/b.tar.gz"             }, {{ ".tar", ".gz"        }}},
    {{ "/a/b.tar.gz"            }, {{ ".tar", ".gz"        }}},
    {{ "a/trailing.dot."        }, {{ ".dot", "."          }}},
    {{ "/a/trailing.dot."       }, {{ ".dot", "."          }}},
    {{ "photo"                  }, {{                      }}},
    {{ "photo.jpg"              }, {{ ".jpg"               }}},
    "windows",
    {{ "c:"                     }, {{                      }}},
    {{ "c:/"                    }, {{                      }}},
    {{ "c:a/b"                  }, {{                      }}},
    {{ "c:/a/b"                 }, {{                      }}},
    {{ "c:a/b.lua"              }, {{ ".lua"               }}},
    {{ "c:/a/b.lua"             }, {{ ".lua"               }}},
    {{ "c:a/.hgrc"              }, {{                      }}},
    {{ "c:/a/.hgrc"             }, {{                      }}},
    {{ "c:a/.hg.rc"             }, {{ ".rc"                }}},
    {{ "c:/a/.hg.rc"            }, {{ ".rc"                }}},
    {{ "c:a/b.tar.gz"           }, {{ ".tar", ".gz"        }}},
    {{ "c:/a/b.tar.gz"          }, {{ ".tar", ".gz"        }}},
    {{ "//My.lua/Share.php"     }, {{                      }}},
    {{ "//My.lua/Share.php/a/b" }, {{                      }}},
    {{ "c:a/trailing.dot."      }, {{ ".dot", "."          }}},
    {{ "c:/a/trailing.dot."     }, {{ ".dot", "."          }}},
  },
}

describe("mods.path", function()
  local is_win = runtime.is_windows
  local p = is_win and ntpath or posixpath
  local modes = Set({ "common", "posix", "windows" })

  for fname, v in tbl.spairs(p) do
    it(fmt("path.%s equals %s.%s", fname, (is_win and "ntpath" or "posixpath"), fname), function()
      assert.are_equal(p[fname], v)
    end)
  end

  for fname, cases in tbl.spairs(tests) do
    local mode = "common"
    for i = 1, #cases do
      local entry = cases[i]
      if modes[entry] then
        mode = entry --[[@as string]]
      else
        local params, expected = unpack(entry --[[@as {}]])
        local case_modes = mode == "common" and { "posix", "windows" } or { mode }
        for _, case_mode in ipairs(case_modes) do
          it(fmt("%s(%s) [%s]", fname, args_repr(params), case_mode), function()
            local set_semantics = case_mode == "posix" and path._set_posix_semantics or path._set_windows_semantics
            set_semantics()
            assert.are_same(expected, { path[fname](unpack(params)) })
          end)
        end
      end
    end
  end

  it("cwd()", function()
    assert.are_equal(lfs.currentdir(), path.cwd())
  end)

  it("expandvars()", function()
    with_env({ foo = "bar", ["{foo"] = "baz1", ["{foo}"] = "baz2" }, function()
      assert.are_same({ "foo" }, { posixpath.expandvars("foo") })
      assert.are_same({ "bar bar" }, { posixpath.expandvars("$foo bar") })
      assert.are_same({ "barbar" }, { posixpath.expandvars("${foo}bar") })
      assert.are_same({ "$[foo]bar" }, { posixpath.expandvars("$[foo]bar") })
      assert.are_same({ "$bar bar" }, { posixpath.expandvars("$bar bar") })
      assert.are_same({ "$?bar" }, { posixpath.expandvars("$?bar") })
      assert.are_same({ "bar}bar" }, { posixpath.expandvars("$foo}bar") })
      assert.are_same({ "${foo" }, { posixpath.expandvars("${foo") })
      assert.are_same({ "baz1}" }, { posixpath.expandvars("${{foo}}") })
      assert.are_same({ "barbar" }, { posixpath.expandvars("$foo$foo") })
      assert.are_same({ "$bar$bar" }, { posixpath.expandvars("$bar$bar") })
    end)
  end)
end)
