name: Tests
# Runs Busted tests across supported platforms and Lua versions.

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    uses: luamod/.github/.github/workflows/tests.yml@main
    with:
      lua_versions: '["luajit","5.1","5.2","5.3","5.4"]'
      luarocks_deps: |
        busted
        inspect
