name: Tests
# Runs Busted tests across supported platforms and Lua versions.

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-posix:
    uses: luamod/.github/.github/workflows/tests.yml@main
    with:
      runner: ubuntu-latest
      lua_versions: '["5.1","5.2","5.3","5.4","5.5","luajit"]'
      luarocks_cache_path: |
        ~/.cache/luarocks
        ~/.luarocks
      luarocks_deps: |
        busted
        inspect

  test-windows:
    uses: luamod/.github/.github/workflows/tests.yml@main
    with:
      runner: windows-latest
      lua_versions: '["5.1","5.2","5.3","5.4","5.5","luajit"]'
      luarocks_cache_path: |
        ~/AppData/Local/LuaRocks/Cache
        ~/AppData/Roaming/LuaRocks
      luarocks_deps: |
        busted
        inspect
